### ISSUE TITLE
Tasmoadmin does not start

### ISSUE THREAD

**Issue by Lawrencezarb** [reloxx13/TasmoAdmin#112]
I know I must be doing some very basically wrong, but I followed the Windows installation instructions and when I http to my local IP address all I see is "index of/".

What am I missing?

**Comment by RaymondMouthaan** [comment]
Hai @Lawrencezarb , Sorry for the delay. I've downloaded [tasmoadmin_v1.0.1_xampp_portable](https://github.com/reloxx13/TasmoAdmin/releases/download/v1.0.1/tasmoadmin_v1.0.1_xampp_portable.zip) followed the instructions from [Windows](https://github.com/reloxx13/TasmoAdmin/blob/master/README.md#windows) and got TasmoAdmin running. I needed to change the apache listening port, because port 80 was occupied. 

![xampp](https://user-images.githubusercontent.com/25717738/40607705-85e5f2fa-6269-11e8-9dfa-f180847b839c.png)

Click the button `Config` and open `Apache (httpd.conf)`, this opens notepad. Look up for:

`Listen 80`

and change it to

`Listen 81` or a diffenent port not in use.

Save and exit notepad and start Apache from the XAMPP control  panel.

**Comment by Lawrencezarb** [comment]
Hi Raymond, Thats great. its working now. 

Thanks for your help

**Comment by RaymondMouthaan** [comment]
@Lawrencezarb glad it worked out for you 👍 . Have fun using TasmoAdmin :-)
