### ISSUE TITLE
Feature Request: Auto Restart

### ISSUE THREAD

**Issue by nhorvath** [reloxx13/TasmoAdmin#114]
My devices tend to lock up if left running for too long (especially the sonoff t1 uk, which requires me to go flip the breaker off and on). Since you are already pulling uptime, and already have the ability to send restart commands, it would be nice if there was an option for if uptime hit a certain number of days to send a restart command automatically.

Great project!

**Comment by nhorvath** [comment]
@ascillato I've seen the timer stuff and used it to turn the output off or on, however I don't see any examples of how to use timers to execute an arbitrary command, like reset. What would the timer config look like to do that?

**Comment by ascillato** [comment]
Hi,

All the information is on Tasmota's Wiki at:

* https://github.com/arendst/Sonoff-Tasmota/wiki/Commands
* https://github.com/arendst/Sonoff-Tasmota/wiki/Rules

And also in some tasmota's issues this was addressed.

One approach for that could be:

Set a **timer** to the time you want to reset and instead of selecting for the output the state ON or OFF, select **RULE**

Then got to the console and type:

```
rule 1
rule on Clock#Timer=1 do Restart 1 endon
```

`Rule 1` means to turn on rules. The rest means that when your timer1 is triggered, do a restart.

Hope this helps with your issue.

Your request to TasmoAdmin is also valid. But for that you have already any of the home automation systems that have lots of scripts and automations for doing all the stuff you want.

Mainly, _TasmoAdmin_ is an administrative tool for Tasmota's devices, so you can upload new firmware to all your devices, set some configurations, etc. etc.

For controlling and for automations, are already some dedicated tools. Example: HomeAssistant, Domoticz, OpenHab, etc.

For HomeAssistant is also available _TasmoAdmin_ as an ADD-ON.

**Comment by lolo888** [comment]
tks for rule, work fine 

rule 1
rule on Clock#Timer=1 do Restart 1 endon

**Comment by Micha70** [comment]
Is also possible to restart only once per week?
I have following configuration:

```
19:17:16.724 CMD: rule 1
19:17:16.736 MQT: stat/LED-Hausflur/RESULT = {"Rule1":{"State":"ON","Once":"ON","StopOnError":"OFF","Length":35,"Free":476,"Rules":"on Clock#Timer=6 do Restart 1 endon"}}
19:18:57.547 MQT: stat/LED-Hausflur/RESULT = {"Timer1":{"Enable":1,"Mode":0,"Time":"03:00","Window":0,"Days":"0100000","Repeat":1,"Output":1,"Action":3}}
 
```

Expected one reset each Monday night. But is resting each night.
I'm using ESP32-Devkit, precompiled with version 11.1.0.

**Comment by VictorLamoine** [comment]
This is the simplest way I have found to make your Tasmota device reboot periodically:
```
RULE1 ON System#Boot DO RuleTimer1 60 ENDON
RULE2 ON Rules#Timer=1 DO Restart 1 ENDON
RULE1 ON
RULE2 ON
```

In this example the device will reboot every 60 seconds
