### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by stoehrmark** [reloxx13/TasmoAdmin#120]
This Codeing looks excelent. Thank You

I am unable to use the SelfUpdate page. Get the following error.
Setup is Windows Xampp, Not the portable version.
Just copied the tasmoadmin_v1.0.3.zip files into my existing XAMPP

I would realy like to intigrate into Home Assistant but i dont have the HASSIO version (built on rasbian).  
I will work on figuring out that install in future.

Curl Error - 60: SSL certificate problem: unable to get local issuer certificate	
Please check your internet connection

![untitled](https://user-images.githubusercontent.com/24501941/40886949-f58bae16-670e-11e8-81e9-35ff3e47bedc.png)

**Comment by stoehrmark** [comment]
![untitled2](https://user-images.githubusercontent.com/24501941/40887098-39314048-6711-11e8-8247-024bfb0f6368.png)

**Comment by reloxx13** [comment]
1. image selfupdate)
this should work now. this happens if the travis build fails. added error handling for this case today, so it will show you a better error message instead of line 49.

2. image device update)
which language did you choose for the automatic mode?
looks like the tasmota bin in your selected language could not getting find.
