### ISSUE TITLE
Autoupdate does not work when using another port than 80 on docker

### ISSUE THREAD

**Issue by tubalainen** [reloxx13/TasmoAdmin#122]
Hi!

Docker magic line:
`docker run -it -v /home/tuben/tasmoadmin:/data -p 8091:80 -e APACHE_SERVER_NAME=tasmoadmin.localnetwork --name tasmoadmin raymondmm/tasmoadmin:latest`

Problem:
My "outside" port is 8091 and the port to access the internal webserver is forced to 80 when trying to perform autoupdate.

Suggestion of solution: Change "OTA server IP" to "OTA Server URL" so that we can specify the port... Or just add the possibility to change port. :) Thanks!

![image](https://user-images.githubusercontent.com/26795429/40903416-927102a8-67d7-11e8-923c-18ca5a8a951f.png)

**Comment by RaymondMouthaan** [comment]
Not related to your issue, but worth to mention ... Since the name change from SonWeb to TasmoAdmin, TasmoAdmin is based on NGINX instead of Apache, so your in your command is not correct, the environment variable can be removed.

```
-e APACHE_SERVER_NAME=tasmoadmin.localnetwork
```

Related to your issue .. TasmoAdmin runs internally on port 80 and gets exposed to a port defined by user or by docker automatically. This is the port to access TasmoAdmin from external. 
For updating devices an connection from internal to external is required, so from within the docker container to your ota server. I agree, it would be more flexible for users to enter the full url of the ota server #69 instead of its ip address only, but in this case if your ota server serves at port 80, it should work.

**Comment by tubalainen** [comment]
@RaymondMouthaan Well.. If I use -p 80:80 all is fine, but if I use -p 8091:80 the URL sent to the sonoffs "OTA Url" (ref till my picture above) is still port 80 and the OTA server resides within the docker .. hence no connection from the sonoffs to the OTA server (Webserver). The "OTA Url" must be http://192.168.21.10:**8091**/data/firmware/sonoff.bin instead of port 80 to be accessed from "outside" the docker container.

Okay on the -e APACHE part, I just follwed the example on the wiki.

**Comment by RaymondMouthaan** [comment]
I think I understand your point, devices get the OTA url from TasmoAdmin which is fixed at port 80, but from the outside it is port 8091. This means the device is not able to get the firmware from TasmoAdmin. 

When the url is fully configureable then the issue should be solved, in other words implementing #69 would be very nice...

**Comment by reloxx13** [comment]
the port should be detected automatically from the url you are calling the webpage

what is your url inside the browser url bar? 

try it like this and than call the update function:
http://192.168.21.10:8091

**Comment by reloxx13** [comment]
configurable port added with next release, reopen it if the issue still exists.
