### ISSUE TITLE
[RFC] Update using local firmware

### ISSUE THREAD

**Issue by timstanley1985** [reloxx13/TasmoAdmin#160]
Hi,

Firstly tasmoadmin is great and had been a bit of a revelation for me as I have a dozen tasmo sonoffs and maintaining them is now so much easier.  I host tasmoadmin on an rpi and compile my own tasmo firmware on the same rpi. At the moment to update my sonoffs I have to compile, scp the firmware onto my phone and then upload via the web interface which feels a bit clumsy.  Can an option be added whereby I can copy the compiled firmware into a folder within tasmoadmin as part of my build script and then a single button push on the web interface would upload this firmware?

**Comment by reloxx13** [comment]
How about a eg. "select from local" button

you would get a file browser of the server or tasmoadmin folder on the server, ill see what is better or possible.

**Comment by kevsgithub** [comment]
I tend to update mine one or two at a time.
It would be nice that if the files already exist in the data/firmwares folder, to offer to use the existing files rather than upload them every time. I believe this would also solve @timstanley1985 issue.

(p.s. We use a configuration management system for our servers that could also drop the files in as our IOT network does not have access to internet it cant get them from github even if we wanted to)

**Comment by reloxx13** [comment]
ill close this as "wont fix" for now.

take a look at this:
https://github.com/arendst/Sonoff-Tasmota/tree/development/tools/fw_server

this will be much easier for you i think on a berry.


another now possible way would be:
- copy fullfirmware as "sonoff.bin" in the data/firmware dir of tasmoadmin
- copy min firmware as "sonoff-minimal.bin" in the data/firmware dir of tasmoadmin
- set ota url of the devices to your server/tasmoadmin/data/firmware/sonoff.bin
- trigger update command with the new command box at the bottom of the device list in tasmoadmin

with the magic ota of tasmota, it will select teh min if the full does not fit in the flahs and than get the full automated.
