### ISSUE TITLE
Question: Help / Tutorial for installing on a RasPi (OpenHABianPi image)

### ISSUE THREAD

**Issue by Jason2866** [reloxx13/TasmoAdmin#171]
Hi,
i use and like Tasmota! I have a few more devices and TasmoAdmin is the right toy now...
Since i am not a programmer nor a Linux guy, i would need a tutorial for installing
TasmoAdmin on a RasPi where the OpenHABianPi image is installed and running.
Is this in general possible? The Pi has enough performance left. OpenHab needs only about 10% of
proccessor performance. Most time less than that.
Maybe there is not so much difference to Ubuntu? But i am lost here.
Thank you!

**Comment by reloxx13** [comment]
i think it will work, openHAB image is based on rasbian and rasbian is based on debian.

you should ask openhab if its okay to install docker or if their will make problems.

check if docker is already installed (sudo docker).



if docker is installed, you could just follow the docker guide for tasmoadmin.

**Comment by RaymondMouthaan** [comment]
if running docker is not an option, you could use the [Ubuntu guide] (https://github.com/reloxx13/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04) to install it on Raspbian, just take note that Rasbian swell as Ubuntu are both Debian based, but not the same. Could be that some required packages (see Ubuntu guide) are not available for Rasbian.

**Comment by Jason2866** [comment]
I asked in OpenHab community forum
https://community.openhab.org/t/intall-docker-on-openhabianpi-for-tasmoadmin/47546
The answer from Markus Storm (one of the Open Hab gurus) wasnt positiv...

**Comment by reloxx13** [comment]
i would still just try it, tasmoadmin runs fine on raspberry and docker.
you should check how much resources openhab uses of the raspberry (cpu/mem/temp).

make a backup of the sd card or just use another one and clone the openhab sd on it and than install docker and tsamoadmin on the new one.

if you can wait, ill just try it myself (but with a clean openhab image and just basic configurations).

**Comment by Jason2866** [comment]
@reloxx13 
Thanks for trying this setup. Would be perfect if you write down the things you do after OpenHab is installed in the case that all works together! I am not a Linux "hero"... I get things runnig if the are documented and/or logic. I dont need a beginner tutorial but the mandantory steps.

**Comment by reloxx13** [comment]
i just installed it on the openhasbian raspberry 3b+

same steps like rasbian, but dotn forget it was a clean and empty openhasbian instalation.

```
#install docker

curl -sSL https://get.docker.com | sh

#create dirs for Docker Volumes(data)
mkdir /home/openhabian/Docker/Portainer/data -p
mkdir /home/openhabian/Docker/TasmoAdmin/data -p


#install Portainer
sudo docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v /home/openhabian/Docker/Portainer/data:/data --name=Portainer --restart=always portainer/portainer

#install tasmoadmin
sudo docker run -d -p 5555:80 -v /home/openhabian/Docker/TasmoAdmin/data:/data --name=TasmoAdmin --restart=always raymondmm/tasmoadmin
```

Portainer page on http://RaspberryIP:9000
TasmiAdmin page on http://RaspberryIP:5555

**Comment by Jason2866** [comment]
Thank you reloxx13👍😃
Will backup my OpenHab system and go to install as you described (some time this weekend).
I cant believe that is going to be as simple as it shines...
Greets Jason2866

**Comment by Jason2866** [comment]
Worked perfect!!! just did 1:1 as you described :-)
I will run the system for a few days "under investigation", but for now i see no unwanted side effects.exit.
System seems relaxed:
![image](https://user-images.githubusercontent.com/24528715/42733154-cf80f354-882c-11e8-95a4-1bb632d77416.png)

**Comment by Jason2866** [comment]
Noob questions:
- What is Portainer? And for what is it used?
- How to upgrade TasmoAdmin (if newer versions availible)?
THX again

Jason2866

**Comment by RaymondMouthaan** [comment]
@Jason2866
if it runs stable, you could consider running OpenHab as docker container as well and when one rpi isn't enough, you could consider to used docker swarm with multiple rpi's in a cluster. 

[Portainer](https://portainer.io) is a management tool (web gui) to manage docker nodes. 

If you want to upgrade to a newer version of TasmoAdmin, you could use Portainer or from command line like this:

```
sudo docker container stop TasmoAdmin
sudo docker container rm TasmoAdmin
sudo docker pull raymondmm/tasmoadmin
sudo docker run -d -p 5555:80 -v /home/openhabian/Docker/TasmoAdmin/data:/data --name=TasmoAdmin --restart=always raymondmm/tasmoadmin
```

Since your TasmoAdmin configuration and devices are stored out-side the container, it's save to remove the container and create a new one with the same path to the TasmoAdmin data.

**Comment by Jason2866** [comment]
@RaymondMouthaan 
Thank you for your explanations.  Cool possibilities :-)  I have too google (once again - autumn, winter job)
i will keep the upgrade howto on a save place ;-)

**Comment by Jason2866** [comment]
@RaymondMouthaan 
Smart Power Metering? Any news?

**Comment by RaymondMouthaan** [comment]
@Jason2866, fully off-topic but .. the measuring works great with tasmota and serial. Currently i am using \n as the delimiter, so that each line gets published to mqtt. I think that would be most handy to parse the required data in Node-Red. As we speak I am re-setting up my Docker Swarm, which will run all  my Home Automation containers (i.e. node-red, clustered mqtt, grafana and many others). As soon as Node-red is up and running I will play with the parsing part and write the measured values to an InfluxDB, then with Grafana I can query InfluxDB to create a nice graph  of those measurements :-)

**Comment by lloydatron** [comment]
Hi, firstly thanks for all the dev re Tasmoadmin it a great tool. I am bumping this thread to find out if anyone successfully got Tasmoadmin running on a Pi directly rather than via docker? I have an openhabian Pi4 setup for which I tried following the Linux instal guide [https://github.com/reloxx13/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04](url) (noticed this is from 2018).

Unfortunately, my limited knowledge of Linux is very apparent and so I am looking for some pointers. 
I managed to get apache up and running but when trying to access via browser (port:9999) I had a message saying something about could not find blah blah. Unfortunately, I can not tell you exactly what blah blah is as once I restarted everything apache2 would not and will not start. 

`Jul 05 11:59:26 openhab apachectl[2387]: AH00558: apache2: Could not reliably determine the server's
Jul 05 11:59:26 openhab apachectl[2387]: (2)No such file or directory: AH02291: Cannot access direct
Jul 05 11:59:26 openhab apachectl[2387]: (2)No such file or directory: AH02291: Cannot access direct
Jul 05 11:59:26 openhab apachectl[2387]: (2)No such file or directory: AH02291: Cannot access direct
Jul 05 11:59:26 openhab apachectl[2387]: AH00014: Configuration check failed
Jul 05 11:59:26 openhab apachectl[2387]: Action 'start' failed.
Jul 05 11:59:26 openhab apachectl[2387]: The Apache error log may have more information.
Jul 05 11:59:26 openhab systemd[1]: apache2.service: Control process exited, code=exited, status=1/F
Jul 05 11:59:26 openhab systemd[1]: apache2.service: Failed with result 'exit-code'.
Jul 05 11:59:26 openhab systemd[1]: Failed to start The Apache HTTP Server.
`
Before I start picking at this and fault finding I wanted to see if anyone else has made this all work.
