### ISSUE TITLE
Add device password field as password not text input

### ISSUE THREAD

**Issue by kevsgithub** [reloxx13/TasmoAdmin#184]
Should the add device password field be a password or text input?

It'll stop the browser auto suggestion box and automatic storing of the password.

Not a huge issue, but I stupidly use the same password for Tasmoadmin and Tasmota web interface.

**Comment by RaymondMouthaan** [comment]
Just to visualise the issue ..

![screen shot 2018-07-15 at 09 06 37](https://user-images.githubusercontent.com/25717738/42731491-6a0aaa6a-880e-11e8-95ce-5cbfee4e1975.png)

**Comment by reloxx13** [comment]
heya, 
i can also disable the remember function of the browser i think.

this pw will also be saved in the csv unhashed and plain.

i cannot hash it since i have to send it to the device in plain.


for secruity reasons you really should change one of the passwords, without SSL this send command with the plain pw can easily be catched if this bad guy is in your wifi/network.

**Comment by RaymondMouthaan** [comment]
@reloxx13, you could store the encrypted pwd in file and decrypt it before sending to Tasmota. This at least makes sure that the password is not plain text when it is stored outside the container. 

I agree with all other arguments concerning security and I guess it's not really adding something... 😬
