### ISSUE TITLE
Suggestions on installation on a Mac, OSX 10.13

### ISSUE THREAD

**Issue by TLCary** [reloxx13/TasmoAdmin#193]
Apache2 is preinstalled, but a bit odd compared to Ubuntu.  I can use homebrew  to install php-curl and php-zip mods.  But there is no sites-enabled directory, www-data:www-data, a2ensite command, etc.
I get the login page but it I get "Not Found" if I try any menus or buttons.
ie: tasmoadmin/tasmoadmin/start. "Not Found"
Suggestions?

**Comment by reloxx13** [comment]
be sure the .htaccess file is in the root dir of tasmoadmin.

on unix/mac systems "." files are hidden.


also check this SO for the missing directory
https://stackoverflow.com/questions/2121159/what-is-the-mac-equivalent-of-etc-apache2-sites-available


i used [MAMP](https://www.mamp.info) on mac, but if you configured your preinstalled apache now, im sure it will conflict with MAMP and you will need to fix it by hand. this is tricky if you are unexp with the console and youll need alot to google 🗡

**Comment by reloxx13** [comment]
you could also try docker on mac

https://docs.docker.com/docker-for-mac/

and use the tasmoadmin docker image

**Comment by TLCary** [comment]
I would really prefer to use the docker image.  I've never used docker and the functionality would be great.  I thought docker images had to be CPU specific and the only docker images are for the ADM and ARM CPUs?  Is there one up there that would work with a Mac (Intel)?    I see a lot of people struggle with Apple's quirky Apache2 install and most people dump it and go with a different install if they need to do anything special.  I'll go that route if I need to.  THANK YOU! For the software and the help.

**Comment by RaymondMouthaan** [comment]
@TLCary,

As @reloxx13 suggested, you can install Docker for MAC. For testing purpose I just ran tasmoadmin in a Docker container running on my macOS High Sierra and it works. The command is (like on the wiki page):

- docker run -it -p 8888:80 --name tasmoadmin-test raymondmm/tasmoadmin

I did not apply the -v (volume option) since this is for testing only, but in your case you should persist the tasmota data outside the docker container. See wiki how to do that.

TasmoAdmin Docker images support manifest list, this means there is no need to specify the tag / architecture. Docker will auto-detect which one you need. You your case I pulls the amd64 image and probably works on macOS.

Cheers :-)

**Comment by TLCary** [comment]
That worked great, (and beats spending time trying to figure out where Apple put stuff when they installed Apache2).  Thanks! Recap for people looking to run this on Mac:
1. Install Docker, (by default it adds the Users directory for file sharing with a container)
2.     docker run -it -v /Users/Shared/host/data:/data -p 8888:80 --name tasmoadmin raymondmm/tasmoadmin
3. http://localhost:8888
