### ISSUE TITLE
Automatic download of Minimal FW and applying full FW not working

### ISSUE THREAD

**Issue by radokristof** [reloxx13/TasmoAdmin#260]
I have tried the Automatic method for updating a Sonoff switch through TasmoAdmin.
It said that the firmware is found, selected the device to update, however it uploaded the full firmware first... after a little wait, it said that it has been upgraded, but not, the version number is the same.

What I'm missing? Where I can specify that it should install the minimal first?

Thanks!

**Comment by reloxx13** [comment]
it will do it automatical, thats tasmotas OTA Magic (check the tasmota wiki for more infos regarding this).

if the update is not working, its properly because the tasmoadmin ota server url is wrong or not reachable.

you can see the url in the logs while updateing, try to call the url with your browser and check if the fw download starts.

tasmotas otamagic does not give a response if it was successfull or not, so atm there is no way to check if it was successfull or not. its more "hey device, here is the url where you find the fw, do your stuff".

**Comment by MaceMoneta** [comment]
> They all get the 6.4.1(minimal) first.
> Then just a few get the full firnware 6.4.1(sonoff). It seems, that all my sonoff pows and S20 do get the full firmware, but the basics get stuck with the minimal.

I'm having exactly the same problem.

**Comment by radokristof** [comment]
> > They all get the 6.4.1(minimal) first.
> > Then just a few get the full firnware 6.4.1(sonoff). It seems, that all my sonoff pows and S20 do get the full firmware, but the basics get stuck with the minimal.
> 
> I'm having exactly the same problem.

I have managed to get auto-update working, but the Basic modules stay on Minimal.
If I press manually the start upgrade from it's web server (the same OTA IP URL which is set in TasmoAdmin) it updates itself.

**Comment by ajfriesen** [comment]
@radokristof I also did update them manually and it worked.
But I think I uploaded my sonoff.bin by hand.

Neither way there is something odd happening.

**Comment by GasTurbineMan** [comment]
I have been seeing similar issues updating my devices with my modified .bin files.  Odd thing is that I had selected a batch of 3 Sonoff Basics and 2 ESP01 devices for upgrade.  All 5 reported that update was successful however only the 2 ESP01's actually showed the updated version.  The basics were later successfully updated via the webgui.

Not sure this is the issue, but seems my update issues started after updating to 6.4.0 to 6.4.1.2. and likewise trying to update to 6.4.1.4.  Using Tasmoadmin on one of the Basics that would not update, I reverted back to 6.1.x which went well and then updated to 6.4.1.2 and all worked well.

**Comment by radokristof** [comment]
I'm using the original release from Tasmota with my Sonoffs, no custom modified firmware (as I suppose, you do some modifications in the firmware). But I think somehow this is related to Tasmota and not TasmoAdmin. Or not?
If I'm right, the minimal and normal selection is done by the firmware and not by TasmoAdmin. So basically what the TasmoAdmin does is downloads the binary firmware file and request an update on the selected devices with the link to the firmware. Tasmota recognizes that this firmware won't fit into the memory, so downloads the minimal firmware (but how? From Github? If yes, why does TasmoAdmin pre-loads the firmware on the device, running TasmoAdmin? Why not let the Sonoff itself download the firmware and additionally download the minimal firmware? Only optional to use local link to update firmware (for custom firmwares)).

Also the 6.4.1 firmware seems buggier for me, than 5.1.x was.

**Comment by reloxx13** [comment]
heyaaaa,


ill update my devices tonight and check it. 

tasmoadmin downloads the minimal and full firmware from the tasmota github.
after that it provides the fw just as @radokristof  descriped.
instead of every device starting to download minimal and full fw over internet, they download it from your local tasmoadmin server.

since this "otamagic" got added, i cannot get feedback back from the device if the new fw was successfull or not.

to debug, you can try to enter the firmware url, written in the update log, in ur browser and see if the download starts. this have to work, if not, the sonoffs wont receive the fw neither.

for @ajfriesen  it would be this line:
`[25-12-2018 12:21:33][ID-8][STEP-2][OTAURL] OTA Url => http://192.168.178.60:9541/data/firmwares/sonoff.bin`

`http://192.168.178.60:9541/data/firmwares/sonoff.bin`

and additional open the devices GUI in ur webbrowser and look at the logs, the update process and errors is written there.

**Comment by radokristof** [comment]
@reloxx13 
Thanks for specifying how this really works!
I have tried the link as well, it download the right firmware for me. Is there a link to the minimal as well?
Also links should work (I think), because other devices got updated flawlessly. So I don't think that the links are not good.
How the sonoffs request the minimal firmware? Or when starting the update process, the minimal fw and full fw path are also defined?

**Comment by reloxx13** [comment]
the minimal link gets generated by tasmota, it adds "-minimal" at the end.

like this:
http://192.168.178.60:9541/data/firmwares/sonoff-minimal.bin

**Comment by reloxx13** [comment]
if both files are available, its to 99% an tasmota problem.

if it fails, go on teh devices GUI, go into the console

check if the firmware url is set correctly by entering the command `OtaUrl`.

edit it with command 
`OtaUrl http://TASMOADMIN_IP:TASMADMIN_PORT/data/firmwares/sonoff.bin`

if this is correct, start the upload with the command `Upgrade 1` and look what happens, tasmota should tell what the problem is in the console.

tasmoadmin is doing exactly this.

**Comment by reloxx13** [comment]
i got the same problem with iobroker, but its not lagging for me or i did not notice lagging. i use the TASMOTA_MQTT_LIBRARY.
check the my_user_config.h file to change the MQTT library (ull need to build your own fw than).

u can give my mod version a try, this is just my own pre-configured tasmota and i upload the binaries.
in past there were some changes in the mod, but most of them got meanwhile included in the official tasmoata repo.

https://github.com/reloxx13/Sonoff-Tasmota-Modified/releases
this is the config of my mod:
https://github.com/reloxx13/Sonoff-Tasmota-Modified/blob/modified/sonoff/my_user_config.h

and the builded bins are with arduino esp lib 2.3.0.

**Comment by radokristof** [comment]
Thanks!

First I will monitor the device, maybe I will try resetting it (I have upgraded from an older fw, mainly because of some MQTT issues which seems fixed with this, but introduced new ones).

I will try your mod if this not works well...
