### ISSUE TITLE
Issue with docker

### ISSUE THREAD

**Issue by lucas-apr** [reloxx13/TasmoAdmin#303]
here is a part of my docker-compose:

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    volumes:
      - /config_data/TasmoAdmin/data:/data
    restart: always
    network_mode: host
    ports:
      - "8124:80"

and here is the error in the container:

nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)

I have checked the docker container and it appears that nothing is listening on port 80.

Any ideas?

**Comment by reloxx13** [comment]
i cannot help you here, cause this is your system related.

**Comment by danielcbit** [comment]
For @lucas-apr and other that might have this error in the future.

The issue is due to the "network_mode: host" entry. This means that the host will try to attach to port 80 of your docker host. If you already have something running there in port 80, you will get this error you mentioned in the docker logs.

Simple remove the "network_mode: host" or change the port from 80 to something else when starting the docker.

Hope that helps.
