### ISSUE TITLE
[SUGGESTION] Rename SonWEB to TasmotaWEB

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/TasmoAdmin#81]
@reloxx13 just a suggesting to rename SonWEB to something like TasmotaWEB, since it covers more than Sonoff devices :-). 

![img_0406](https://user-images.githubusercontent.com/25717738/37399139-0aff85f6-2781-11e8-919c-47652314c35d.jpg)

**Comment by reloxx13** [comment]
TasWEB ? :D

i dunno, im moving atm, and will think about it, almost done with the kitchen :D

ill be back in 1-2 weeks 👍

**Comment by RaymondMouthaan** [comment]
Sound nice, TasWeb, TasmoWeb of TasmotaWeb 😇.. 

Good luck with your movement 💪

**Comment by reloxx13** [comment]
TasmoWeb sounds nice for me :D

**Comment by RaymondMouthaan** [comment]
Or even TasmoAdmin sounds nice 😇

**Comment by MimbaMonkeyHouse** [comment]
Personally, I like Tasmollusc!

**Comment by MimbaMonkeyHouse** [comment]
Or TasmoNkey!

**Comment by RaymondMouthaan** [comment]
@MimbaMonkeyHouse that's to hard to pronounce 😂

**Comment by reloxx13** [comment]
still no decision, also it will be a lil bit tricky for the selfupdate, if i rename the git, the selfupdate wouldn't work anymore cuz it cannot find the old git url x.x

**Comment by RaymondMouthaan** [comment]
Just thinking out loud .. what if you just make a fork which you name SonWEB as it is now and rename the current project as one of the suggestion or better .. 

Current deployed / installed instances point to the fork and if it is possible while one tries to SelfUpdate to display a warning message and even better update their location to the new GitHub repo ... 

But maybe thats just to much work for a rename #lol 

Whatever you decide .. SonWeb deserves a better name, just because it does do more than Sonoff only 🥇 👍 .

**Comment by reloxx13** [comment]
sadly, this wont work :S
if i rename the git, the url will changed and the selfupdate wont find the download.

if im lucky, github will redirect it to the new git name, ill need to make a test repo and try what happens if i rename it.

if their is no way around, i need to build a fallback in the selfupdate and give the users some time to update and get the fallback. after some time (1-2month) i could rename it.

fallback like:
look for old url, not found, so look for the new (fallback) url.

**Comment by RaymondMouthaan** [comment]
SonWEB has been renamed to TasmoAdmin 🎉
